<?php
/**
 * Blackbird EstimateTimeShipping Module - Hyva compatibility
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_EstimateTimeShippingHyvaCompatibility
 * @copyright       Copyright (c) 2018 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://store.bird.eu/license/
 * @support         support@bird.eu
 */
?>
<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<?php $date = $block->getOrder()->getData('estimated_delivery_date'); ?>
<?php if ($this->helper('Blackbird\EstimateTimeShipping\Helper\Data')->getHowToDisplay()) : ?>
    <td data-th="<?= $block->escapeHtml(__('Estimated Delivery Date')) ?>" class="col deliverydate text-sm py-2 px-4">
        <?= /* @escapeNotVerified */
        ($date) ? $block->formatDate($date) : '' ?>
    </td>
<?php endif; ?>
