<?php
/**
 * Blackbird EstimateTimeShipping Module - Hyva compatibility
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_EstimateTimeShippingHyvaCompatibility
 * @copyright       Copyright (c) 2018 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://store.bird.eu/license/
 * @support         support@bird.eu
 */
/* @var \Blackbird\EstimateTimeShipping\Block\Order\Item $block */
?>
<?php if (!$block->getHowToDisplay()) : ?>
<div class="edd-date rounded p-2 my-2 bg-blue-50 text-blue-700 text-sm">
    <?= /** @noEscape */ $block->getEstimatedDate($block->getParentBlock()->getItem()->getData('quote_item_id')); ?>
</div>
<?php endif; ?>
